### ISSUE TITLE
Hosting on AWS

### ISSUE THREAD

**Issue by rasikasamarakoon** [dotnet/eShopOnContainers#1630] opened 2021-03-11 17:31 UTC
Hello team,

I am a .Net developer learning AWS. Would you mind if I take(possibly fork) the source code for eShopOnContainers and try running it using AWS services(As opposed to Azure services). If it is successful I can share it with .Net/AWS community and probably here https://aws.amazon.com/developer/language/net/?whats-new-dotnet.sort-by=item.additionalFields.postDateTime&whats-new-dotnet.sort-order=desc

Thank you in advance.

**Comment by sughosneo** [comment] 2021-03-15 12:31
Hi @rasikasamarakoon, thank you for reaching out and taking the initiative to test out the `eShopOnContainers` application on AWS.

It would be amazing if you could document all the required steps in your blog. We will be happy to link that in our wiki.

**Comment by rasikasamarakoon** [comment] 2021-03-16 01:25
Thank you very much @sughosneo and I will start playing with it. I could be a little slow at he beginning , but I let you guys know how it goes.

**Comment by medvedevden1s** [comment] 2021-05-04 16:52
@rasikasamarakoon any progress on it? 
I would be glad to try to run it on aws, maybe help is needed?? 
I can try to help you

**Comment by rasikasamarakoon** [comment] 2021-05-05 05:29
@medvedevden1s I haven't got far. First I was trying to run it locally and managed get it running with docker compose up.But I had issues running in local kubernetes and so I started learning kubernetes a bit. I am thinking about trying to run it in kubernetes on AWS rather than troubleshooting local kubernetes because it could be some configuration on my computer. 
You your help would be great and let me know if you have any thoughts on how best to proceed.

**Comment by biplovkc** [comment] 2021-07-20 16:26
I would be interested to see if someone managed to solve the event bus implementation with aws technology. I meant something along the line of sns/sqs or event ridge and not rabbitmq.

**Comment by erjain** [comment] 2022-02-01 12:22
Considering the issue is very old and the original question is answered, I am closing this issue for now. Please feel free to open it again if you are looking for more help.

**Closed as completed by erjain** 2022-02-01 12:22 UTC
Labels: AWS
