### ISSUE TITLE
First time running on VS2017: NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by baikinjo** [dotnet/eShopOnContainers#97] opened 2017-03-08 12:07 UTC
After installation guide from wiki, first time running the sln, - web only - gives 2 breaking points:
1. An exception of type 'System.AggregateException' occurred in System.Private.CoreLib.ni.dll but was not handled in user code occurred
2. An unhandled exception of type 'System.Reflection.TargetInvocationException' occurred in System.Private.CoreLib.ni.dll occurred
If I continue, shows this error:
Microsoft.eShopOnContainers.WebMVC.Services.RetryWithExponentialBackoff+<RunAsync>d__4.MoveNext() in C:\eShopOnContainers\src\Web\WebMVC\Services\Utilities\RetryWithExponentialBackoff.cs, line 41

Microsoft.eShopOnContainers.WebMVC.Services.RetryWithExponentialBackoff+<RunAsync>d__4.MoveNext() in C:\eShopOnContainers\src\Web\WebMVC\Services\Utilities\RetryWithExponentialBackoff.cs
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.eShopOnContainers.WebMVC.Services.CatalogService+<GetCatalogItems>d__4.MoveNext() in C:\eShopOnContainers\src\Web\WebMVC\Services\CatalogService.cs
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.eShopOnContainers.WebMVC.Controllers.CatalogController+<Index>d__2.MoveNext() in C:\eShopOnContainers\src\Web\WebMVC\Controllers\CatalogController.cs
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeActionMethodAsync>d__27.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextActionFilterAsync>d__25.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextResourceFilter>d__22.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeAsync>d__20.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__18.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__18.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__18.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__18.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()

Any Suggestion?
btw, I could not find the VS2017 Branch, so I cloned master branch and installation seemed flawless.

**Comment by CESARDELATORRE** [comment] 2017-03-08 17:24
The "the VS2017 Branch" was a typo already fixed in the Wiki. Please, use the MASTER branch.

Sounds like some containers are still not started when launching the solution, we might need to extend the time for the retrys with exponential backoff that we implemented for that case and also for resiliency purposes. 
Could be that your machine is starting the containers much slower than in our dev machines or something similar.
What configuration do you have in your machine?
- Memory
- Processor
- SSD? Hard-Drive?

I'd like to isolate why we don't get this error in our tests when starting it.
I'll try to set a larger timeout at the client retries, for now..
Thanks,

**Comment by CESARDELATORRE** [comment] 2017-03-09 01:11
baikinjo Hey! - So, we couldn't reproduce your issue in our machines, but since the error was related to the code I wrote about the resilient retries with exponential backoff, I guess your machine can be satrting slower and the number of retries waiting for the other containers was not enough time..
So, just in case, I raised the number of retries from 10 to 50.
here's the commit:
https://github.com/dotnet/eShopOnContainers/commit/4469a4b85101b432bd4ee4d049b82a3e274eae45

Please, try again (Git pull first ) and confirm how it goes, ok?
Thanks,

**Comment by baikinjo** [comment] 2017-03-09 05:33
hey, I pulled the newest git and tried again and looks like I am having the same issue.

1. Processor: Intel Core i5-4300U @1.90GHz 2.49GHz
2. Memory: 8.00GB
3. SSD

I will try the CLI method now and keep you guys posted.
Thanks!

**Comment by baikinjo** [comment] 2017-03-09 06:09
UPDATE: 
Using CLI Method, after finishing .NET bits, when I run docker-compose up it shows this error:
![image](https://cloud.githubusercontent.com/assets/13024845/23738064/a9e2edc0-044b-11e7-8155-cc28312a3ac7.png)

also including my docker version as well
when I run docker-compose build seems working but not up

**Comment by CESARDELATORRE** [comment] 2017-03-09 19:10
Looks like an ifrastructure issue with "Docker for Windows".
Is any other Docker application working/deploying/running on that machine?
Can you try that a Hello ASP.NET Core Web app with Docker enables works on your machine?
If not, then I'd say that it is a "Docker for Windows" infrastructure isse. Related to the network/ports in your development machine or related to Hyper-V.
Please, check Docker's trobuleshooting for that.
https://docs.docker.com/toolbox/faqs/troubleshoot/

If other apps do work on Docker, then reply and we'll keep researching, but we couldn't reproduce that issue.

**Comment by Blood13** [comment] 2017-03-11 06:28
Hello!
Same issue here. 
When i open localhost:5100 it send request to Catalog.API (GET api/v1/[controller]/items[?pageSize=3&pageIndex=10]). 
Error raised on 
`var totalItems = await _context.CatalogItems.LongCountAsync();` function.
Exception here: 
![default](https://cloud.githubusercontent.com/assets/881433/23821208/92f18f3e-063c-11e7-8b8a-6509a9ebe368.png)
I don't have any other containers. My pc config is i5 2500k, 8gb ram, 120gb SSD.

**Comment by CESARDELATORRE** [comment] 2017-03-12 05:32
Looks like it is not the same issue. baikinjo is getting errors when trying to start the containers, like "Cannot start service catalog.api: driver failed... etc." - That looks like a Docker infrastructure issue that we are not able to repro in our dev machines. Need to check it out with Docker's trobuleshooting for that and or try other Docker container projects to isolate the infrastructure issue.
https://docs.docker.com/toolbox/faqs/troubleshoot/

In regards Blood13 issues, looks like a network issue that we  cannot repro, neither. 
It the SPA app working for you? - http://localhost:5104  - Please, confirm.

**Comment by grahamehorner** [comment] 2017-03-25 14:31
I'm also seeing the above exception, my system is

i7-7500 2.7ghz
16Gb RAM
256Gb SSD

**Closed** 2017-04-18 20:41 UTC

**Comment by sbgtrading** [comment] 2017-12-07 14:49
I just installed VS2017, and ported over a VS2013 winforms app that has been running well for years.  I attempted to run it, and VS2017 is throwing multiple null reference exceptions.  Crazy things like the various check boxes on the form...when I examine their "Checked" value, I get a null reference error.

My .Net version is 4.6.01532...is that the problem?  Does it need to get updated?

Any suggestions?

**Comment by CESARDELATORRE** [comment] 2017-12-07 18:00
@sbgtrading Has that issue anything to do with eShopOnContainers that uses .NET Core? - You are mentioning WinForms...
.NET version in your WinForms app shouldn't need to be updated.
If this is a completely issue not related to eShopOnContainers, please, I suggest you open an issue about it in the Visual Studio issues, here:
https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017
Best thing to do is if you can upload a small project into your GitHub account reproducing the issues, and point to it from the issue.
Then, if you'd like, send me an email with the issue's URL so I can send it to folks in the VS team, ok?

**Comment by sbgtrading** [comment] 2017-12-07 19:27
Thanks for the response Cesar...I'm not using any eShopOnContainers code or calls.  

When I run the form, and the debugger launches from the exception, I notice that the debugger has "optimized away" some other variables (like a DateTime variable)...and it's value is not accessible.  That DateTime variable is not what caused the exception, it's typically failing on a check box ".Checked" property, but is it possible that the check box object has been "optimized away" as well?
