### ISSUE TITLE
docker-compose build has error

### ISSUE THREAD

**Issue by KGwolf** [dotnet/eShopOnContainers#1767] opened 2021-10-01 14:50 UTC
Restore operation started...
/root/.nuget/packages/microsoft.web.librarymanager.build/2.1.113/build/Microsoft.Web.LibraryManager.Build.targets(35,9): error : Microsoft.Web.LibraryManager.Contracts.ResourceDownloadException: Failed to download resource from "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/core.js" [/src/Web/WebStatus/WebStatus.csproj]
/root/.nuget/packages/microsoft.web.librarymanager.build/2.1.113/build/Microsoft.Web.LibraryManager.Build.targets(35,9): error :  ---> System.Net.Http.HttpRequestException: Cannot assign requested address (cdnjs.cloudflare.com:443) [/src/Web/WebStatus/WebStatus.csproj]
/root/.nuget/packages/microsoft.web.librarymanager.build/2.1.113/build/Microsoft.Web.LibraryManager.Build.targets(35,9): error :  ---> System.Net.Sockets.SocketException (99): Cannot assign requested address [/src/Web/WebStatus/WebStatus.csproj]
/root/.nuget/packages/microsoft.web.librarymanager.build/2.1.113/build/Microsoft.Web.LibraryManager.Build.targets(35,9): error :    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) [/src/Web/WebStatus/WebStatus.csproj]
/root/.nuget/packages/microsoft.web.librarymanager.build/2.1.113/build/Microsoft.Web.LibraryManager.Build.targets(35,9): error :    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) [/src/Web/WebStatus/WebStatus.csproj]
/root/.nuget/packages/microsoft.web.librarymanager.build/2.1.113/build/Microsoft.Web.LibraryManager.Build.targets(35,9): error :    at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken) [/src/Web/WebStatus/WebStatus.csproj]
/root/.nuget/packages/microsoft.web.librarymanager.build/2.1.113/build/Microsoft.Web.LibraryManager.Build.targets(35,9): error :    at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken) [/src/Web/WebStatus/WebStatus.csproj]
/root/.nuget/packages/microsoft.web.librarymanager.build/2.1.113/build/Microsoft.Web.LibraryManager.Build.targets(35,9): error :    at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken) [/src/Web/WebStatus/WebStatus.csproj]
/root/.nuget/packages/microsoft.web.librarymanager.build/2.1.113/build/Microsoft.Web.LibraryManager.Build.targets(35,9): error :    --- End of inner exception stack trace --- [/src/Web/WebStatus/WebStatus.csproj]
/root/.nuget/packages/microsoft.web.librarymanager.build/2.1.113/build/Microsoft.Web.LibraryManager.Build.targets(35,9): error :    at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken) [/src/Web/WebStatus/WebStatus.csproj]
/root/.nuget/packages/microsoft.web.librarymanager.build/2.1.113/build/Microsoft.Web.LibraryManager.Build.targets(35,9): error :    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) [/src/Web/WebStatus/WebStatus.csproj]
/root/.nuget/packages/microsoft.web.librarymanager.build/2.1.113/build/Microsoft.Web.LibraryManager.Build.targets(35,9): error :    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) [/src/Web/WebStatus/WebStatus.csproj]
/root/.nuget/packages/microsoft.web.librarymanager.build/2.1.113/build/Microsoft.Web.LibraryManager.Build.targets(35,9): error :    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) [/src/Web/WebStatus/WebStatus.csproj]
/root/.nuget/packages/microsoft.web.librarymanager.build/2.1.113/build/Microsoft.Web.LibraryManager.Build.targets(35,9): error :    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) [/src/Web/WebStatus/WebStatus.csproj]
/root/.nuget/packages/microsoft.web.librarymanager.build/2.1.113/build/Microsoft.Web.LibraryManager.Build.targets(35,9): error :    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) [/src/Web/WebStatus/WebStatus.csproj]
/root/.nuget/packages/microsoft.web.librarymanager.build/2.1.113/build/Microsoft.Web.LibraryManager.Build.targets(35,9): error :    at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken) [/src/Web/WebStatus/WebStatus.csproj]
/root/.nuget/packages/microsoft.web.librarymanager.build/2.1.113/build/Microsoft.Web.LibraryManager.Build.targets(35,9): error :    at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) [/src/Web/WebStatus/WebStatus.csproj]
/root/.nuget/packages/microsoft.web.librarymanager.build/2.1.113/build/Microsoft.Web.LibraryManager.Build.targets(35,9): error :    at Microsoft.Web.LibraryManager.Cache.WebRequestHandler.GetStreamAsync(String url, CancellationToken cancellationToken) [/src/Web/WebStatus/WebStatus.csproj]
/root/.nuget/packages/microsoft.web.librarymanager.build/2.1.113/build/Microsoft.Web.LibraryManager.Build.targets(35,9): error :    --- End of inner exception stack trace --- [/src/Web/WebStatus/WebStatus.csproj]
/root/.nuget/packages/microsoft.web.librarymanager.build/2.1.113/build/Microsoft.Web.LibraryManager.Build.targets(35,9): error :    at Microsoft.Web.LibraryManager.Cache.WebRequestHandler.GetStreamAsync(String url, CancellationToken cancellationToken) [/src/Web/WebStatus/WebStatus.csproj]
/root/.nuget/packages/microsoft.web.librarymanager.build/2.1.113/build/Microsoft.Web.LibraryManager.Build.targets(35,9): error :    at Microsoft.Web.LibraryManager.Cache.CacheService.DownloadToFileAsync(String url, String fileName, Int32 attempts, CancellationToken cancellationToken) [/src/Web/WebStatus/WebStatus.csproj]
/root/.nuget/packages/microsoft.web.librarymanager.build/2.1.113/build/Microsoft.Web.LibraryManager.Build.targets(35,9): error :    at Microsoft.Web.LibraryManager.Cache.CacheService.<>c__DisplayClass9_0.<<RefreshCacheAsync>g__DownloadFileIfNecessaryAsync|0>d.MoveNext() [/src/Web/WebStatus/WebStatus.csproj]
/root/.nuget/packages/microsoft.web.librarymanager.build/2.1.113/build/Microsoft.Web.LibraryManager.Build.targets(35,9): error : --- End of stack trace from previous location --- [/src/Web/WebStatus/WebStatus.csproj]
/root/.nuget/packages/microsoft.web.librarymanager.build/2.1.113/build/Microsoft.Web.LibraryManager.Build.targets(35,9): error :    at Microsoft.Web.LibraryManager.Utilities.ParallelUtility.DoActionAndRelease[T](Func`2 act, T input, SemaphoreSlim s) [/src/Web/WebStatus/WebStatus.csproj]
/root/.nuget/packages/microsoft.web.librarymanager.build/2.1.113/build/Microsoft.Web.LibraryManager.Build.targets(35,9): error :    at Microsoft.Web.LibraryManager.Utilities.ParallelUtility.ForEachAsync[T](Func`2 action, Int32 degreeOfParallelism, IEnumerable`1 items, CancellationToken cancellationToken) [/src/Web/WebStatus/WebStatus.csproj]
/root/.nuget/packages/microsoft.web.librarymanager.build/2.1.113/build/Microsoft.Web.LibraryManager.Build.targets(35,9): error :    at Microsoft.Web.LibraryManager.Cache.CacheService.RefreshCacheAsync(IEnumerable`1 librariesCacheMetadata, ILogger logger, CancellationToken cancellationToken) [/src/Web/WebStatus/WebStatus.csproj]
/root/.nuget/packages/microsoft.web.librarymanager.build/2.1.113/build/Microsoft.Web.LibraryManager.Build.targets(35,9): error :    at Microsoft.Web.LibraryManager.Providers.BaseProvider.RefreshCacheAsync(ILibraryInstallationState state, CancellationToken cancellationToken) [/src/Web/WebStatus/WebStatus.csproj]
libman.json : error LIB010: Failed to download resource from "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/core.js" [/src/Web/WebStatus/WebStatus.csproj]

  One or more libraries failed to restore

ERROR: Service 'webstatus' failed to build: The command '/bin/sh -c dotnet publish --no-restore -c Release -o /app' returned a non-zero code: 1
PS G:\GitHubProjects\eShopOnContainers\src>

**Comment by KGwolf** [comment] 2021-10-01 14:53
but I can get  "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/core.js" by google browser

**Comment by KGwolf** [comment] 2021-10-01 14:59
I can run the project by vs , so i dont konw why

**Comment by sughosneo** [comment] 2021-10-04 09:57
Hi @KGwolf , thank you for reaching out.  Could you please clean up old docker images and build the docker images again?

- To do clean up 

```text

docker stop $(docker ps -aq)
docker rm $(docker ps -aq)
docker volume rm $(docker volume ls -q)

```

> !IMPORTANT: Above commands will clean up all running containers and it's data in your MacOS/Workstation.

- Enable `docker.for.linux.localhost` hostname for the docker in the following file. 

https://github.com/dotnet-architecture/eShopOnContainers/blob/46219957ef763305030a0924d039fe4a25831b06/src/.env#L16

- To run the app 
- Go to the `/src/` directory

```text
docker-compose up sqldata
```
Once it's ready to accept the new connection, then you can bring up the other container by using the following command from a separate terminal window.

```text
docker-compose up
```

**Comment by sughosneo** [comment] 2021-10-11 09:01
Hi @KGwolf, just checking if you had a chance to look into this further. Thank you.

**Comment by xieyiincuit** [comment] 2021-10-15 09:09
I have the same question and I change the version of Jquery in WebStatus, but error like "Failed to download resource from "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/core.js"" occurred in other services which use  libman to fetch jquery or bootStarp .

**Comment by KGwolf** [comment] 2021-10-15 09:29
Hi @sughosneo ,Thank you for answering my question.

'Enable docker.for.linux.localhost hostname for the docker in the following file.', Is this the right way for running the container in Windows?

 i cleaned containers and images,then use the 'docker-compose build' command to running,but there are still problems.

**Comment by KGwolf** [comment] 2021-10-15 09:33
@xieyiincuit I suspect it's our network problem

**Comment by xieyiincuit** [comment] 2021-10-17 12:27
> @xieyiincuit I suspect it's our network problem
If you solved this problem, pls told me... xiexie!

**Comment by sughosneo** [comment] 2021-10-18 15:07
Hi @KGwolf, after reviewing the stack trace `Microsoft.Web.LibraryManager.Contracts.ResourceDownloadException: Failed to download resource from "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/core.js" `
one more time, it seems like there could be an issue in your environment as well. I would agree with @xieyiincuit

Is your machine behind any firewall which is blocking the access of `"https://cdnjs.cloudflare.com`?
Could you please test the application from another environment if possible?

**Comment by sughosneo** [comment] 2021-10-18 15:07
This issue could be duplicate of https://github.com/dotnet-architecture/eShopOnContainers/issues/1735

**Comment by sughosneo** [comment] 2021-10-21 10:43
> ```shell
> > [eshop/identity.api:linux-latest build 39/39] RUN dotnet publish --no-restore -c Release -o /app:
> #544 3.455 Microsoft (R) Build Engine version 16.11.1+3e40a09f8 for .NET
> #544 3.455 Copyright (C) Microsoft Corporation. All rights reserved.
> #544 3.455
> #544 4.670
> #544 4.670   Restore operation started...
> #544 19.44 libman.json : error LIB002: The "jquery@3.3.1" library could not be resolved by the "cdnjs" provider [/src/Services/Identity/Identity.API/Identity.API.csproj]
> #544 19.44
> #544 19.44   One or more libraries failed to restore
> #544 19.44
> ```
> 
> This is my first time running this so not sure what I am missing. Dev build downloaded today.

@neil-thompson-sapphire  - This seems to be a similar error mentioned above.

**Comment by sughosneo** [comment] 2021-10-28 08:37
> Hi @KGwolf, after reviewing the stack trace `Microsoft.Web.LibraryManager.Contracts.ResourceDownloadException: Failed to download resource from "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/core.js" ` one more time, it seems like there could be an issue in your environment as well. I would agree with @xieyiincuit
> 
> Is your machine behind any firewall which is blocking the access of `"https://cdnjs.cloudflare.com`? Could you please test the application from another environment if possible?

Did you have a chance to test out the functionality in an environment? Thank you.

**Comment by sughosneo** [comment] 2021-11-01 11:00
I am closing this issue as of now. Please feel free to reopen if needed. Thank you.

**Closed as completed by sughosneo** 2021-11-01 11:00 UTC
Labels: docker-compose
