### ISSUE TITLE
[QUESTION] Why there is ArgumentNullException all over the code?

### ISSUE THREAD

**Issue by zenkraker** [dotnet/eShopOnContainers#1602] opened 2021-02-03 14:47 UTC
Why there is ArgumentNullException inside almost every constructor of the project? For example inside CatalogController there is at line 29
 _logger = logger ?? throw new **ArgumentNullException(nameof(logger));**

Why this? sorry for the noob question

**Comment by sughosneo** [comment] 2021-02-08 13:21
Hi @zenkraker, thank you for reaching out. 

As per [creating-and-throwing-exceptions](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/exceptions/creating-and-throwing-exceptions), one of the reason a method should throw an exception when it can't complete it's defined functionality.  In case if you are throwing `System.ArgumentNullException`, it typically means that you want to make sure that non-null object is passed to that method whenever it gets called. For more details you could refer [CA1062: Validate arguments of public methods](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1062?view=vs-2019). You could look at it as "fail fast" approach. This behavior is same for the constructor as well.  For e.g `_logger = logger ?? throw new ArgumentNullException(nameof(logger));` in `OrdersController` or any other classes. With this approach you can make sure, whenever you are using `_logger` private variable within this class context it shouldn't be turning out to be `Null` and ends up throwing a `NullReferenceException` error.  ASP.NET Core by design supports [Dependency injection](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-5.0), where each object of dependent classes gets passed on to other class over constructor arguments, and that's the reason validating objects within the constructor makes more meaningful than elsewhere. 
Please note that, few of the object interface for e.g `ILogger` gets injected to the constructor by default. Similarly you could also register and inject your custom classes as well. For e.g : `IIdentityService` in `OrdersController`

Hope this helps !

**Comment by william-li-ry** [comment] 2021-02-13 13:07
Just an advise, if you can try to debug it, it will be easier to know why your argument is null. Also another reason maybe that your environment is not fully set up. However if more info can be provided, for example, your environment of this happening, or under which senario this occurs, it's easier for other people to identify the issue. Cheers.

**Comment by sughosneo** [comment] 2021-03-23 09:32
It seems like the original question on this issue has already been answered. So I am closing this as of now. 
Please feel free to reopen it, if needed.

Thank you.

**Closed as completed by sughosneo** 2021-03-23 09:32 UTC
Labels: question
